<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PKBank.Core</RootNamespace>
    <Description>Supplemental game data and logic not provided by PKHeX.Core</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\packages\PKHeX\PKHeX.Core\PKHeX.Core.csproj" />
  </ItemGroup>

</Project>
